package src.fr_departments;

public class FR_AllDepartments {
  /*
   * On trouve ici la liste de tous les départements français, décrits avec leur
   * numéro, leur nom, leur préfecture (chef-lieu), leurs sous-préfectures.
   *
   * On fera attention au fait que la Corse n'est pas bien traitée : elle
   * apparaît comme un unique département alors qu'actuellement (2022) elle en
   * comporte deux ; mais pour la numérotation et la représentation d'un graphe
   * de voisinage des départements français, il est considérablement plus simple
   * de la considérer comme un unique département, de numéro 20. Comme les deux
   * départements qui la constituent sont exclusivement limitrophes l'un de
   * l'autre, dans une application de calcul de plus courts chemins, ce n'est
   * pas très restrictif
   */
  public static final int DEPARTMENT_COUNT = 95 ;
  private static final FR_Department[] department ;
  /*
   * Attention, les départements sont numérotés à partir de 1 mais le tableau
   * est indexé à partir de 0, évidemment...
   */
  public static FR_Department getDepartment(int dept) {
    return department[dept-1] ;
  }
  static {
    department = new FR_Department[DEPARTMENT_COUNT] ;
    // This part initializing the array was generated by awk
    department[  0] = new FR_Department("001", "Ain", "Bourg-en-Bresse", "Belley", "Gex", "Nantua") ;
    department[  1] = new FR_Department("002", "Aisne", "Laon", "Château-Thierry", "Saint-Quentin", "Soissons", "Vervins") ;
    department[  2] = new FR_Department("003", "Allier", "Moulins", "Montluçon", "Vichy") ;
    department[  3] = new FR_Department("004", "Alpes-de-Haute-Provence", "Digne-les-Bains", "Barcelonnette", "Castellane", "Forcalquier") ;
    department[  4] = new FR_Department("005", "Hautes-Alpes", "Gap", "Briançon") ;
    department[  5] = new FR_Department("006", "Alpes-Maritimes", "Nice", "Grasse") ;
    department[  6] = new FR_Department("007", "Ardèche", "Privas", "Largentière", "Tournon-sur-Rhône") ;
    department[  7] = new FR_Department("008", "Ardennes", "Charleville-Mézières", "Rethel", "Sedan", "Vouziers") ;
    department[  8] = new FR_Department("009", "Ariège", "Foix", "Pamiers", "Saint-Girons") ;
    department[  9] = new FR_Department("010", "Aube", "Troyes", "Bar-sur-Aube", "Nogent-sur-Seine") ;
    department[ 10] = new FR_Department("011", "Aude", "Carcassonne", "Limoux", "Narbonne") ;
    department[ 11] = new FR_Department("012", "Aveyron", "Rodez", "Millau", "Villefranche-de-Rouergue") ;
    department[ 12] = new FR_Department("013", "Bouches-du-Rhône", "Marseille", "Aix-en-Provence", "Arles", "Istres") ;
    department[ 13] = new FR_Department("014", "Calvados", "Caen", "Bayeux", "Lisieux", "Vire Normandie") ;
    department[ 14] = new FR_Department("015", "Cantal", "Aurillac", "Mauriac", "Saint-Flour") ;
    department[ 15] = new FR_Department("016", "Charente", "Angoulême", "Cognac", "Confolens") ;
    department[ 16] = new FR_Department("017", "Charente-Maritime", "La Rochelle", "Jonzac", "Rochefort", "Saintes", "Saint-Jean-d'Angély") ;
    department[ 17] = new FR_Department("018", "Cher", "Bourges", "Saint-Amand-Montrond", "Vierzon") ;
    department[ 18] = new FR_Department("019", "Corrèze", "Tulle", "Brive-la-Gaillarde", "Ussel") ;
    department[ 19] = new FR_Department("020", "Corse", "Ajaccio", "Bastia", "Sartène", "Calvi", "Corte") ;
    department[ 20] = new FR_Department("021", "Côte-d'Or", "Dijon", "Beaune", "Montbard") ;
    department[ 21] = new FR_Department("022", "Côtes-d'Armor", "Saint-Brieuc", "Dinan", "Guingamp", "Lannion") ;
    department[ 22] = new FR_Department("023", "Creuse", "Guéret", "Aubusson") ;
    department[ 23] = new FR_Department("024", "Dordogne", "Périgueux", "Bergerac", "Nontron", "Sarlat-la-Canéda") ;
    department[ 24] = new FR_Department("025", "Doubs", "Besançon", "Montbéliard", "Pontarlier") ;
    department[ 25] = new FR_Department("026", "Drôme", "Valence", "Die", "Nyons") ;
    department[ 26] = new FR_Department("027", "Eure", "Évreux", "Les Andelys", "Bernay") ;
    department[ 27] = new FR_Department("028", "Eure-et-Loir", "Chartres", "Châteaudun", "Dreux", "Nogent-le-Rotrou") ;
    department[ 28] = new FR_Department("029", "Finistère", "Quimper", "Brest", "Châteaulin", "Morlaix") ;
    department[ 29] = new FR_Department("030", "Gard", "Nîmes", "Alès", "Le Vigan") ;
    department[ 30] = new FR_Department("031", "Haute-Garonne", "Toulouse", "Muret", "Saint-Gaudens") ;
    department[ 31] = new FR_Department("032", "Gers", "Auch", "Condom", "Mirande") ;
    department[ 32] = new FR_Department("033", "Gironde", "Bordeaux", "Arcachon", "Blaye", "Langon", "Lesparre-Médoc", "Libourne") ;
    department[ 33] = new FR_Department("034", "Hérault", "Montpellier", "Béziers", "Lodève") ;
    department[ 34] = new FR_Department("035", "Ille-et-Vilaine", "Rennes", "Fougères", "Redon", "Saint-Malo") ;
    department[ 35] = new FR_Department("036", "Indre", "Châteauroux", "Le Blanc", "La Châtre", "Issoudun") ;
    department[ 36] = new FR_Department("037", "Indre-et-Loire", "Tours", "Chinon", "Loches") ;
    department[ 37] = new FR_Department("038", "Isère", "Grenoble", "La Tour-du-Pin", "Vienne") ;
    department[ 38] = new FR_Department("039", "Jura", "Lons-le-Saunier", "Dole", "Saint-Claude") ;
    department[ 39] = new FR_Department("040", "Landes", "Mont-de-Marsan", "Dax") ;
    department[ 40] = new FR_Department("041", "Loir-et-Cher", "Blois", "Romorantin-Lanthenay", "Vendôme") ;
    department[ 41] = new FR_Department("042", "Loire", "Saint-Étienne", "Montbrison", "Roanne") ;
    department[ 42] = new FR_Department("043", "Haute-Loire", "Le Puy-en-Velay", "Brioude", "Yssingeaux") ;
    department[ 43] = new FR_Department("044", "Loire-Atlantique", "Nantes", "Châteaubriant", "Saint-Nazaire") ;
    department[ 44] = new FR_Department("045", "Loiret", "Orléans", "Montargis", "Pithiviers") ;
    department[ 45] = new FR_Department("046", "Lot", "Cahors", "Figeac", "Gourdon") ;
    department[ 46] = new FR_Department("047", "Lot-et-Garonne", "Agen", "Marmande", "Nérac", "Villeneuve-sur-Lot") ;
    department[ 47] = new FR_Department("048", "Lozère", "Mende", "Florac-Trois-Rivières") ;
    department[ 48] = new FR_Department("049", "Maine-et-Loire", "Angers", "Cholet", "Saumur", "Segré-en-Anjou Bleu") ;
    department[ 49] = new FR_Department("050", "Manche", "Saint-Lô", "Avranches", "Cherbourg-en-Cotentin", "Coutances") ;
    department[ 50] = new FR_Department("051", "Marne", "Châlons-en-Champagne", "Épernay", "Reims", "Vitry-le-François") ;
    department[ 51] = new FR_Department("052", "Haute-Marne", "Chaumont", "Langres", "Saint-Dizier") ;
    department[ 52] = new FR_Department("053", "Mayenne", "Laval", "Château-Gontier", "Mayenne") ;
    department[ 53] = new FR_Department("054", "Meurthe-et-Moselle", "Nancy", "Lunéville", "Toul", "Val de Briey") ;
    department[ 54] = new FR_Department("055", "Meuse", "Bar-le-Duc", "Commercy", "Verdun") ;
    department[ 55] = new FR_Department("056", "Morbihan", "Vannes", "Lorient", "Pontivy") ;
    department[ 56] = new FR_Department("057", "Moselle", "Metz", "Forbach", "Sarrebourg", "Sarreguemines", "Thionville") ;
    department[ 57] = new FR_Department("058", "Nièvre", "Nevers", "Château-Chinon", "Clamecy", "Cosne-Cours-sur-Loire") ;
    department[ 58] = new FR_Department("059", "Nord", "Lille", "Avesnes-sur-Helpe", "Cambrai", "Douai", "Dunkerque", "Valenciennes") ;
    department[ 59] = new FR_Department("060", "Oise", "Beauvais", "Clermont", "Compiègne", "Senlis") ;
    department[ 60] = new FR_Department("061", "Orne", "Alençon", "Argentan", "Mortagne-au-Perche") ;
    department[ 61] = new FR_Department("062", "Pas-de-Calais", "Arras", "Béthune", "Boulogne-sur-Mer", "Calais", "Lens", "Montreuil", "Saint-Omer") ;
    department[ 62] = new FR_Department("063", "Puy-de-Dôme", "Clermont-Ferrand", "Ambert", "Issoire", "Riom", "Thiers") ;
    department[ 63] = new FR_Department("064", "Pyrénées-Atlantiques", "Pau", "Bayonne", "Oloron-Sainte-Marie") ;
    department[ 64] = new FR_Department("065", "Hautes-Pyrénées", "Tarbes", "Argelès-Gazost", "Bagnères-de-Bigorre") ;
    department[ 65] = new FR_Department("066", "Pyrénées-Orientales", "Perpignan", "Céret", "Prades") ;
    department[ 66] = new FR_Department("067", "Bas-Rhin", "Strasbourg", "Haguenau", "Molsheim", "Saverne", "Sélestat") ;
    department[ 67] = new FR_Department("068", "Haut-Rhin", "Colmar", "Altkirch", "Mulhouse", "Thann") ;
    department[ 68] = new FR_Department("069", "Rhône", "Lyon", "Villefranche-sur-Saône") ;
    department[ 69] = new FR_Department("070", "Haute-Saône", "Vesoul", "Lure") ;
    department[ 70] = new FR_Department("071", "Saône-et-Loire", "Mâcon", "Autun", "Chalon-sur-Saône", "Charolles", "Louhans") ;
    department[ 71] = new FR_Department("072", "Sarthe", "Le Mans", "La Flèche", "Mamers") ;
    department[ 72] = new FR_Department("073", "Savoie", "Chambéry", "Albertville", "Saint-Jean-de-Maurienne") ;
    department[ 73] = new FR_Department("074", "Haute-Savoie", "Annecy", "Bonneville", "Saint-Julien-en-Genevois", "Thonon-les-Bains") ;
    department[ 74] = new FR_Department("075", "Paris", "Paris") ;
    department[ 75] = new FR_Department("076", "Seine-Maritime", "Rouen", "Dieppe", "Le Havre") ;
    department[ 76] = new FR_Department("077", "Seine-et-Marne", "Melun", "Fontainebleau", "Meaux", "Provins", "Torcy") ;
    department[ 77] = new FR_Department("078", "Yvelines", "Versailles", "Mantes-la-Jolie", "Rambouillet", "Saint-Germain-en-Laye") ;
    department[ 78] = new FR_Department("079", "Deux-Sèvres", "Niort", "Bressuire", "Parthenay") ;
    department[ 79] = new FR_Department("080", "Somme", "Amiens", "Abbeville", "Montdidier", "Péronne") ;
    department[ 80] = new FR_Department("081", "Tarn", "Albi", "Castres") ;
    department[ 81] = new FR_Department("082", "Tarn-et-Garonne", "Montauban", "Castelsarrasin") ;
    department[ 82] = new FR_Department("083", "Var", "Toulon", "Brignoles", "Draguignan") ;
    department[ 83] = new FR_Department("084", "Vaucluse", "Avignon", "Apt", "Carpentras") ;
    department[ 84] = new FR_Department("085", "Vendée", "La Roche-sur-Yon", "Fontenay-le-Comte", "Les Sables-d'Olonne") ;
    department[ 85] = new FR_Department("086", "Vienne", "Poitiers", "Châtellerault", "Montmorillon") ;
    department[ 86] = new FR_Department("087", "Haute-Vienne", "Limoges", "Bellac", "Rochechouart") ;
    department[ 87] = new FR_Department("088", "Vosges", "Épinal", "Neufchâteau", "Saint-Dié-des-Vosges") ;
    department[ 88] = new FR_Department("089", "Yonne", "Auxerre", "Avallon", "Sens") ;
    department[ 89] = new FR_Department("090", "Territoire de Belfort", "Belfort") ;
    department[ 90] = new FR_Department("091", "Essonne", "Évry-Courcouronnes", "Étampes", "Palaiseau") ;
    department[ 91] = new FR_Department("092", "Hauts-de-Seine", "Nanterre", "Antony", "Boulogne-Billancourt") ;
    department[ 92] = new FR_Department("093", "Seine-Saint-Denis", "Bobigny", "Le Raincy", "Saint-Denis") ;
    department[ 93] = new FR_Department("094", "Val-de-Marne", "Créteil", "L'Haÿ-les-Roses", "Nogent-sur-Marne") ;
    department[ 94] = new FR_Department("095", "Val-d'Oise", "Pontoise", "Argenteuil", "Pontoise", "Sarcelles") ;
  }
}
